library(aricode)
library(readxl)

###############################################################
# Compare gene clusters using adjusted rand index
###############################################################
gene_nums <- c(1000,2000,3000,4000,5000,6000)
clusters <- lapply(1:length(gene_nums), function(x) x)
names(clusters) <- as.character(gene_nums)
gene_to_evalute = c() # These are genes in the clusters when '1000' genes were used as inputs

# Get cluster assignments in each input setting (gene size)
# When only look at cluster assignments for genes in 'gene_to_evaluate'
# and see if their assignments are invariant acorss different setting
# These cluster assignments were generated from scSTEM GUI using the files in ../data/input/human_immune
for(num in gene_nums){
  
  file_name <- paste0("../data/cluster_assignments_different_inputs/",
                 num,
                 "genes_NKpath_cluster_genes.xlsx")
  
  # Get all sheet names of an excel table
  sheets <- excel_sheets(file_name)
  assignments <- c()
  
  # For each sheet get cluster assignments for all genes
  for(i in 1:length(sheets)){
    tab <- read_excel(file_name, sheet = sheets[i])
    tmp <- tab$gene_id
    names(tmp) <- rep(as.character(i),length(tmp))
    assignments <- c(assignments,tmp)
  }
  if(num == 1000){
    gene_to_evalute <- assignments
    clusters[[as.character(num)]] <- assignments
  }
  else{
    
    # Here we get cluster assignments for gene in 'gene_to_evaluate'
    tmp1 <- intersect(gene_to_evalute, assignments)
    tmp2 <- setdiff(gene_to_evalute, assignments)
    tmp3 <- assignments[assignments %in% tmp1]
    final <- c(tmp3, tmp2)
    names(final)[(length(tmp3)+1):length(final)] <- as.character(sample(10:1000, size = length(tmp2), replace = F))
    final <- final[match(gene_to_evalute, final)] # Change to same order
    clusters[[as.character(num)]] <- final
  }
  
}

# Compute the adjusted rand index to compare cluster assignments in different input settings.
mat <- matrix(nrow = 6, ncol = 6, NA)
rownames(mat) <- names(clusters)
colnames(mat) <- names(clusters)
for(i in 1:length(clusters)){
  for(j in 1:length(clusters)){
    mat[i,j] <- ARI(names(clusters[[i]]),names(clusters[[j]]))
  }
}

# Perform randomized clustering and generate empirical distributions of adjusted rand index.
# Empirical distributions were generated by using the randomly generating the same number of clusters observed from the previous step. 
# Based on this, we can get an empirical p-value for each ARI value calculated in the previous step.
cluster_nums <- unlist(lapply(clusters, function(x) length(unique(names(x)))))
mat_pval <- matrix(nrow = 6, ncol = 6, NA)
rownames(mat) <- names(clusters)
colnames(mat) <- names(clusters)
for(i in 1:length(clusters)){
  if(i < length(clusters)){
    for(j in (i+1):length(clusters)){
      
      # Randomly generate cluster assignments 10000 times.
      ari_distri <- lapply(1:10000, function(k){
          assignments1 <- sample(cluster_nums[i],length(clusters[[i]]),replace = T)
          assignments2 <- sample(cluster_nums[j],length(clusters[[j]]),replace = T)
          ARI(assignments1, assignments2)
        }
      )
      
      # A distribution of ARI
      ari_distri <- unlist(ari_distri)
      
      # Pvalue matrix
      mat_pval[i,j] <- sum(ari_distri > mat[i,j])/length(ari_distri)
    }
  }
}

# Symmetrize pvalue matrix
mat_pval[lower.tri(mat_pval)] <- t(mat_pval)[lower.tri(mat_pval)]

# Correct pvalues
mat_pval[lower.tri(mat_pval)] <- p.adjust(mat_pval[lower.tri(mat_pval)], method = "BH")
mat_pval[upper.tri(mat_pval)] <- p.adjust(mat_pval[upper.tri(mat_pval)], method = "BH")

# Diagonal of p-value matrix not to be used
diag(mat_pval) <- 1

# Replace pvalues by significance symbols
for(i in 1:length(clusters)){
  for(j in 1:length(clusters)){
    if(mat_pval[i,j] < 0.001){
      mat_pval[i,j] = "***"
    }else if(mat_pval[i,j] < 0.01){
      mat_pval[i,j] = "**"
    }else if(mat_pval[i,j] < 0.05){
      mat_pval[i,j] = "*"
    }else{
      mat_pval[i,j] = ""
    }
  }
}

svg(file = "../results/figS10A_heatmap.svg",
    width = 7,
    height = 7
)

# Get heatmap
pheatmap(mat,
          main = "ARI for Different Number of Genes",
          color = colorRampPalette(c("#FFFFFF","#3A6FCB"))(1000),
          border_color = NA,
          display_numbers = mat_pval,
          fontsize_number = 26,
          fontsize = 15,
          cluster_cols = F,
          cluster_rows = F,
          angle_col = "0",
          legend_breaks = c(0,0.25,0.50,0.75,1)
          )

# Save heatmap
dev.off()
